project:
  type: website
  output-dir: docs

website:
  title: "Google Search"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true



